[project]
name = "srt-resync-web"
version = "0.1.0"
description = "Upload srt file for resyncing"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.0",
    "werkzeug>=3.1.3",
]
